version: '3'

services:
  proxy:
    build: .
    ports: 
      - 127.0.0.1:8080:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ui
      - api

  ui:
    build: ui
    environment:
      UID: 100000

  api:
    build: api
    environment:
      UID: 100001
