version: '3'

services:
  proxy:
    build: .
    ports: 
      - 127.0.0.1:8080:80
    depends_on:
      - ui
      - api

  ui:
    build: ui
    environment:
      UID: 100000

  api:
    build: api
    environment:
      UID: 100001
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: devdb
